### ISSUE TITLE
Force NTP sync takes forever

### ISSUE THREAD

**Issue by ghost** [rackerlabs/ansible-kafka#8]
Hi, I'm running script on a single Ubuntu 16.04 VM, when ansible reaches to "common : Force NTP sync" it hangs with no progress, when I run `/usr/sbin/ntpd -gq` manually I see lots `Soliciting pool server` messages and apparently it never stops and I have to comment this step in playbook

**Comment by grierdavid** [comment]
Thank you for the comment. I normally utilize the CentOS images when I deploy, but I'll try to take the time to look soon. 

What type of VM are you running and where is it located (aws,rackspace,etc)?

**Comment by ghost** [comment]
I'm using ESX VM running on our local servers
